# Generated by Django 5.0.7 on 2024-08-01 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0004_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='archived',
        ),
    ]
