# Generated by Django 5.0.7 on 2024-08-01 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0006_product_archived'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name']},
        ),
    ]
